# Generated by Django 5.1.1 on 2024-10-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("porfolio", "0002_alter_project_options_alter_project_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Dirección web"),
        ),
    ]
